project:
  type: website
  output-dir: _site

bibliography: references.bib
csl: csl/econometrica.csl

website:
  title: "ad688-employability-Fa2501-group12"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Research"
      - href: data_analysis.qmd
        text: "Data Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true





