project:
  type: website
  output-dir: _site

bibliography: references.bib
csl: csl/econometrica.csl

website:
  title: "ad688-employability-Fa2501-group12"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Research Introduction"
      - href: data_cleaning.qmd/ipynb
        text: "Data Cleaning & Exploration"
      - href: eda.qmd/ipynb
        text: "Exploratory Data Analysis"
      - href: skill_gap_analysis.qmd/ipynb
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd/ipynb
        text: "ML Methods"
      - href: nlp_methods.qmd/ipynb
        text: "NLP Methods"
      - href: career_plan.qmd
        text: "Career Plan"
      - href: about.qmd
        text: "About"


format:
  html:
    theme: cosmo
    toc: true

execute:
  echo: true
  eval: true
  code-fold: true





